#!/bin/bash

# WeChat SDK 项目 - 后续开发步骤

echo "=================================================="
echo "WeChat SDK 项目 - 后续开发指南"
echo "=================================================="
echo ""

# 步骤 1: 安装依赖
echo "📦 步骤 1: 安装依赖"
echo "--------------------------------------------"
echo "命令: npm install"
echo "   或: yarn install"
echo "   或: pnpm install"
echo ""

# 步骤 2: 编译 TypeScript
echo "🔨 步骤 2: 编译 TypeScript"
echo "--------------------------------------------"
echo "命令: npm run build"
echo "      npm run dev     (监控模式)"
echo "      npm run type-check"
echo ""

# 步骤 3: 运行测试
echo "🧪 步骤 3: 编写和运行测试"
echo "--------------------------------------------"
echo "命令: npm test"
echo "      npm run test:watch    (监控模式)"
echo "      npm run test:coverage (覆盖率报告)"
echo ""
echo "注意: 需要在 src/__tests__/ 中添加测试文件"
echo ""

# 步骤 4: 实现 QClaw 通道
echo "⚡ 步骤 4: 实现 QClaw 通道"
echo "--------------------------------------------"
echo "文件: src/sdk/channels/qclaw/client.ts"
echo "      src/sdk/channels/qclaw/auth.ts"
echo "      src/sdk/channels/qclaw/types.ts"
echo ""
echo "参考资料:"
echo "  - 原始实现: GitHub 上的 wechat-openclaw-channel"
echo "  - 文档: docs/ARCHITECTURE.md"
echo "  - API 参考: docs/API.md"
echo ""

# 步骤 5: 实现 WorkBuddy 通道
echo "🌐 步骤 5: 实现 WorkBuddy 通道"
echo "--------------------------------------------"
echo "文件: src/sdk/channels/workbuddy/client.ts"
echo "      src/sdk/channels/workbuddy/auth.ts"
echo "      src/sdk/channels/workbuddy/types.ts"
echo ""

# 步骤 6: 更新 SDK 主类
echo "🔧 步骤 6: 更新 SDK 主类以支持通道实现"
echo "--------------------------------------------"
echo "修改: src/sdk/index.ts"
echo "  - createQClawChannel() 方法"
echo "  - createWorkBuddyChannel() 方法"
echo "  - autoSelectMode() 逻辑"
echo ""

# 步骤 7: 发布 npm 包
echo "📤 步骤 7: 发布到 npm（可选）"
echo "--------------------------------------------"
echo "1. 创建 npm 账号: https://www.npmjs.com"
echo "2. 配置 package.json 中的包名和信息"
echo "3. 运行: npm publish"
echo "4. 或使用 npm publish --access public（公开包）"
echo ""

# 推荐的文件编辑顺序
echo "=================================================="
echo "📋 推荐的实现顺序"
echo "=================================================="
echo ""
echo "1️⃣ 创建 QClaw 通道实现"
echo "   ├─ src/sdk/channels/qclaw/types.ts"
echo "   ├─ src/sdk/channels/qclaw/auth.ts"
echo "   └─ src/sdk/channels/qclaw/client.ts"
echo ""
echo "2️⃣ 创建 WorkBuddy 通道实现"
echo "   ├─ src/sdk/channels/workbuddy/types.ts"
echo "   ├─ src/sdk/channels/workbuddy/auth.ts"
echo "   └─ src/sdk/channels/workbuddy/client.ts"
echo ""
echo "3️⃣ 更新 src/sdk/index.ts"
echo "   └─ 完成 createChannel() 方法的实现"
echo ""
echo "4️⃣ 创建单元测试"
echo "   ├─ src/__tests__/sdk.test.ts"
echo "   ├─ src/__tests__/channels.test.ts"
echo "   └─ src/__tests__/message.test.ts"
echo ""
echo "5️⃣ 创建 examples/"
echo "   ├─ src/examples/basic.ts"
echo "   ├─ src/examples/qclaw-login.ts"
echo "   ├─ src/examples/workbuddy-login.ts"
echo "   └─ src/examples/message-handling.ts"
echo ""

echo "=================================================="
echo "✨ 项目资源"
echo "=================================================="
echo ""
echo "📖 主要文档:"
echo "  • README.md - 项目概览"
echo "  • PROJECT_SUMMARY.md - 完成总结"
echo "  • docs/ARCHITECTURE.md - 架构设计"
echo "  • docs/INTEGRATION.md - 集成指南"
echo "  • docs/API.md - API 参考"
echo "  • docs/EXAMPLES.md - 代码示例"
echo "  • docs/TROUBLESHOOTING.md - 故障排查"
echo ""
echo "🔧 核心代码:"
echo "  • src/sdk/index.ts - SDK 主类"
echo "  • src/sdk/types.ts - 类型定义"
echo "  • src/sdk/error.ts - 错误定义"
echo "  • src/sdk/channels/base.ts - Channel 基类"
echo "  • src/sdk/utils/logger.ts - 日志工具"
echo ""

echo "=================================================="
echo "✅ 快速检查清单"
echo "=================================================="
echo ""
echo "[ ] 已安装依赖"
echo "[ ] 已运行 npm run build"
echo "[ ] 已导入类型检查"
echo "[ ] 已实现 QClaw 通道"
echo "[ ] 已实现 WorkBuddy 通道"
echo "[ ] 已创建单元测试"
echo "[ ] 已创建集成测试"
echo "[ ] 已验证所有示例代码"
echo "[ ] 已运行 npm test"
echo "[ ] 已检查代码覆盖率"
echo "[ ] 已更新文档"
echo "[ ] 已发布到 npm"
echo ""

echo "=================================================="
echo "💡 开发建议"
echo "=================================================="
echo ""
echo "1. 使用 TypeScript strict 模式确保类型安全"
echo "2. 为每个方法添加 JSDoc 注释"
echo "3. 编写全面的单元测试（目标 >80% 覆盖率）"
echo "4. 使用 yarn audit 检查依赖安全"
echo "5. 遵循 ESLint 和 Prettier 代码风格"
echo "6. 定期更新依赖包版本"
echo "7. 在发布前进行完整的集成测试"
echo ""

echo "=================================================="
echo "🚀 现在可以开始实现了！"
echo "=================================================="
echo ""
